### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by ajoyej** [stakater-charts/pgadmin#13]
Hello,

While working for one of my private projects, I have taken your helm chart as a basis.
I have added some features like ingress and more customization from within the values.yaml.

If you are interested, I could provide you the update (If you allow me to create a pull request).

Sincerely,
José

**Comment by kahootali** [comment]
Hi, @ajoyej ,

We would love to add these features, please create a PR.

**Comment by ajoyej** [comment]
Hello,
I currently have no right to push my branch
How do you proceed for a pull request in your repo?

Thanks
José 

Envoyé de mon iPhone

**Comment by ahmadiq** [comment]
Hi @ajoyej you should first create a fork of the repository, and then open a pull request from that fork.

**Comment by kahootali** [comment]
Closing the issue as its PR is merged
